steps:
  # Installer les dépendances
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '.'

  # Lancer les tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'test']
    dir: '.'

  # Construire l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA'
      - '.'

  # Pousser l'image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA'

  # Déployer sur GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials lost-treasure-cluster --zone=europe-west1-b
        kubectl set image deployment/frontend-deployment frontend=europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA --namespace production

images:
  - 'europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA'
