options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'pipelines'
      - 'run'
      - '--pipeline=multi-environment-pipeline'
      - '--project=losttreasre'
      - '--region=europe-west1'
      - '--release=dev-release'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'deploy'
      - 'pipelines'
      - 'run'
      - '--pipeline=multi-environment-pipeline'
      - '--project=losttreasre'
      - '--region=europe-west1'
      - '--release=recette-release'

images:
  - 'europe-west1-docker.pkg.dev/losttreasre/lost-treasure-game-front/frontend:$SHORT_SHA'
