apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: multi-environment-pipeline
  namespace: default
spec:
  targets:
    - targetName: dev-target
    - targetName: recette-target
  phases:
    - name: dev
      deploy:
        release:
          name: dev-release
          images:
            - image: europe-west1-docker.pkg.dev/losttreasre/lost-treasure-front/frontend:dev-latest
    - name: recette
      deploy:
        release:
          name: recette-release
          images:
            - image: europe-west1-docker.pkg.dev/losttreasre/lost-treasure-front/frontend:recette-latest