apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
  namespace: default
spec:
  cluster:
    name: dev-cluster
    location: europe-west1
  namespace: dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: recette-target
  namespace: default
spec:
  cluster:
    name: recette-cluster
    location: europe-west1
  namespace: recette